##Importing the Libraries

In [1]:
import numpy as np
import pandas as pd

##Importing the Dataset

In [2]:
df = pd.read_csv('RockVsMine.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [3]:
print(X)

[[0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.01   0.0171 0.0623 ... 0.0044 0.004  0.0117]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


In [4]:
print(y)

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
print(X_train)

[[0.0116 0.0179 0.0449 ... 0.0054 0.0148 0.0092]
 [0.0392 0.0108 0.0267 ... 0.0044 0.0022 0.0014]
 [0.0286 0.0453 0.0277 ... 0.0027 0.0051 0.0062]
 ...
 [0.0363 0.0478 0.0298 ... 0.0114 0.0073 0.0033]
 [0.019  0.0038 0.0642 ... 0.0022 0.0055 0.0122]
 [0.0329 0.0216 0.0386 ... 0.0042 0.0053 0.0074]]


In [8]:
print(y_train)

['M' 'M' 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M'
 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'R' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R'
 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M'
 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'M'
 'M' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'R' 'R' 'M'
 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M'
 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'R'
 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'R' 'M'
 'M' 'R' 'M']


In [9]:
print(X_test)

[[0.009  0.0062 0.0253 ... 0.0053 0.0189 0.0102]
 [0.01   0.0194 0.0155 ... 0.0019 0.0053 0.0019]
 [0.0311 0.0491 0.0692 ... 0.0182 0.0046 0.0038]
 ...
 [0.0094 0.0611 0.1136 ... 0.0168 0.0245 0.0154]
 [0.0654 0.0649 0.0737 ... 0.044  0.0243 0.0098]
 [0.0115 0.015  0.0136 ... 0.0037 0.007  0.0041]]


In [10]:
print(y_test)

['R' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R'
 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M'
 'M' 'M' 'R' 'M' 'M' 'R']


## Training the Logistic Regression model on the Training set

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['R' 'R']
 ['M' 'R']
 ['R' 'R']
 ['R' 'R']
 ['R' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['M' 'R']
 ['R' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'R']
 ['R' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']]


##Checking Accuracy of the model with the confusion matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  4]
 [ 6 14]]


0.7619047619047619

##Checking the Accuracy for the dataset with KNN

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred1 = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

[['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['R' 'R']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)
accuracy_score(y_test, y_pred1)

[[19  3]
 [ 8 12]]


0.7380952380952381

### We came to a conclusion that Logistic Regression gives us a better model than K-NN, So we will preedict a new result with Logistic Regression.

In [22]:
Input_Data = (0.0015,0.0186,0.0289,0.0195,0.0515,0.0817,0.1005,0.0124,0.1168,0.1476,0.2118,0.2575,0.2354,0.1334,0.0092,0.1951,0.3685,0.4646,0.5418,0.6260,0.7420,0.8257,0.8609,0.8400,0.8949,0.9945,1.0000,0.9649,0.8747,0.6257,0.2184,0.2945,0.3645,0.5012,0.7843,0.9361,0.8195,0.6207,0.4513,0.3004,0.2674,0.2241,0.3141,0.3693,0.2986,0.2226,0.0849,0.0359,0.0289,0.0122,0.0045,0.0108,0.0075,0.0089,0.0036,0.0029,0.0013,0.0010,0.0032,0.0047)
# Changing this Input to a Numpy Array
Input_Data_as_Numpy_Array = np.asarray(Input_Data)

# Reshaping the Numpy Array
Input_Data_Reshaped = Input_Data_as_Numpy_Array.reshape(1,-1)

Prediction = classifier.predict(Input_Data_Reshaped)
print(Prediction)

if (Prediction[0]=='R'):
  print('The object is a Rock')
else:
  print('The object is a mine')


['M']
The object is a mine
